### ISSUE TITLE
Traverse across modules with babel plugin

### ISSUE THREAD

**Issue by AxelDelmas** [thejameskyle/babel-handbook#101]
Is it possible to traverse across all bindings of a node across modules with a babel plugin?
Let's say I want to rename a class method: I'll want to rename with a visitor using ClassMethod, and then traverse all bindings to rename it accordingly even in files that import this Class

In the current state of my investigation, it seems to me that it's not possible. It looks like I can only access binding from the same file, and that each module has a distinct AST with no way to traverse import / exports. Is that correct?

**Comment by hzoo** [comment]
Right, currently Babel runs per file - you would have to do some analysis and then run that on all files

**Comment by thejameskyle** [comment]
Yeah I wouldn't try using Babel for refactoring tasks anyways

**Comment by hzoo** [comment]
I would try https://github.com/facebook/jscodeshift

**Comment by AxelDelmas** [comment]
Ok will take a look! Thanks for the tip!
