### ISSUE TITLE
Inserting into a container has incorrect code

### ISSUE THREAD

**Issue by kenzierocks** [thejameskyle/babel-handbook#112]
https://github.com/thejameskyle/babel-handbook/blob/master/translations/en/plugin-handbook.md#user-content-toc-inserting-into-a-container

The code should not have the `.get('body')`, as that returns the actual `body` array. `unshift/pushContainer` is a method on the `path`.

**Comment by hzoo** [comment]
@kenzierocks cool with making a pr to change it? looks like my mistake 😄

**Comment by kenzierocks** [comment]
Yea, I'll do it tonight.
