### ISSUE TITLE
Debugging the AST?

### ISSUE THREAD

**Issue by tmcw** [thejameskyle/babel-handbook#15]
It's useful to see the full AST structure when writing a plugin. The usual suspects - JSON.stringify and console.log - don't work for this purpose. Is there an alternative to output an AST as  formatted string without `[object]` everywhere that it goes more than a step or two deep?

**Comment by fkling** [comment]
You could give http://astexplorer.net/ a try (disclaimer: I maintain this project).

**Comment by tmcw** [comment]
This is for debugging deep in an existing project, where the AST node has been determined by a lot of inference. astexplorer is great, but this usecase is different.

**Comment by thejameskyle** [comment]
This exists: https://github.com/asyncly/cdir

**Comment by tmcw** [comment]
Via Sebastian, `JSON.stringify(require("babel-traverse").removeProperties(node), null, "  ")` also does the trick.

**Comment by tmcw** [comment]
With the es6 default style, that's now

```
var traverse = require("babel-traverse").default;
JSON.stringify(traverse.removeProperties(node), null, " ")
```

But I'm confident that this actually works all the time. To be clear about how this is a very different usecase than ast-explorer or cdir would solve: I'm working on a project that uses documentation.js internally, and in its test suite it has `t.deepEqual` between fixtures and babel objects. With babel's default node structure, there are cycles and methods that both make nodes way different than plain old javascript objects, and more critically, make at least node-tap's deepEqual method fall into an infinite loop.

**Comment by tmcw** [comment]
Thanks for the input - using current versions of babel works for this issue!
