### ISSUE TITLE
Add introduction of NodePath::get and NodePath::pushContainer/unshiftContainer

### ISSUE THREAD

**Issue by hax** [thejameskyle/babel-handbook#16]
I found these methods are useful but not easy to understand :sweat_smile:

**Comment by thejameskyle** [comment]
We're starting to work on API documentation for the babel-traverse and babel-types packages

**Comment by lijunle** [comment]
@thejameskyle Any update about the documentation?

**Comment by ariporad** [comment]
@thejameskyle: Hey, thanks for this great resource. Any updates on the documentation? Thanks!

**Comment by hzoo** [comment]
Added .get https://github.com/thejameskyle/babel-handbook/blob/master/translations/en/plugin-handbook.md#get-the-path-of-sub-node and container https://github.com/thejameskyle/babel-handbook/blob/master/translations/en/plugin-handbook.md#inserting-into-a-container
