### ISSUE TITLE
How to throw errors

### ISSUE THREAD

**Issue by fab1an** [thejameskyle/babel-handbook#24]
What is the preferred way to throw syntax-errors which show source-code which generated it?

**Comment by thejameskyle** [comment]
```js
throw path.buildCodeFrameError('message')
```

**Comment by fab1an** [comment]
Thanks!

**Comment by hzoo** [comment]
https://github.com/thejameskyle/babel-handbook/blob/master/translations/en/plugin-handbook.md#-throwing-a-syntax-error
