### ISSUE TITLE
chinese translate error

### ISSUE THREAD

**Issue by TimCN** [thejameskyle/babel-handbook#59]
In [zh-Hans](https://github.com/thejameskyle/babel-handbook/blob/master/translations/zh-Hans/user-handbook.md), there is a simple translate error.
original: 

> Note:You can't register Babel in the same file that you want to compile. As node is executing the file before Babel has a chance to compile it.

to chinese:

>注意：你不能在你要编译的文件内同时注册 Babel，因为 node 会在 Babel 编译它之间就将它执行了。

When I read the chinese version, it confuse me. Then check the original and make sure this is a translate error.
It's the 

>之间

should be

> 之前

**Comment by thejameskyle** [comment]
We maintain the translations via crowdin, if you want to update it head over here: https://github.com/thejameskyle/babel-handbook/blob/master/CONTRIBUTING.md#translating-the-handbook

**Comment by TimCN** [comment]
Got it. I added my suggestions at crowdin.

**Comment by thejameskyle** [comment]
Cool thanks
