### ISSUE TITLE
How to write tests for the plugin?

### ISSUE THREAD

**Issue by hax** [thejameskyle/babel-handbook#61]
Could the plugin's author use `babel-helper-plugin-test-runner`? Though it's said only for babel internal usage.

**Comment by thejameskyle** [comment]
Explore this directory: https://github.com/thejameskyle/babel-plugin-react-pure-components/tree/master/test

**Comment by hzoo** [comment]
I would copy the file of the index.js james mentioned and then create folders + actual.js/expected.js

there's also https://github.com/thejameskyle/generator-babel-plugin
