### ISSUE TITLE
Plugin api

### ISSUE THREAD

**Issue by AljoschaMeyer** [thejameskyle/babel-handbook#62]
This is a great tutorial for getting started with writing plugins. However, the following are some questions I expected to find some answers to. I'm not specifically asking for these answers, I just think that this information should be part of the handbook. Especially since the babel website links to this as the only documentation for writing plugins - unless I'm missing someting obvious.

Is there a plugin API? What does the return value of a plugin function do? Are properties other than `visitor` supported? If so, where can I see which ones? Can a plugin add type definitions? If so, how?

**Comment by thejameskyle** [comment]
Go to http://slack.babeljs.io for support
