### ISSUE TITLE
Get the file path in the ImportDeclaration

### ISSUE THREAD

**Issue by michaelzoidl** [thejameskyle/babel-handbook#63]
Hi, i'm working on a module which allows to use `~/my-module` instead of `../../../my-module` (it allows a UNIX-like import.

For converting it to the right path i have to use `path.relative` to get the "cd-way", the target-file is easy to get since this is given in the `ImportDeclaration`.
But i need also the start-file, so the file where the `import foo from '../foo';` is written, i didn't saw a documentation for a API-Point for that. 

My Question: is there some kind of API to get the file-path?

Thanks a lot

**Comment by thejameskyle** [comment]
You can get the file path from the `node.source.value` property of an `ImportDeclaration`.

```js
{
  "type": "ImportDeclaration",
  "specifiers": [{
    "type": "ImportDefaultSpecifier",
    "local": {
      "type": "Identifier",
      "name": "foo"
    }
  }],
  "source": {
    "type": "Literal",
    "value": "./foo",
    "raw": "'./foo'"
  }
}
```

See: http://astexplorer.net/#/gob29P1Iw1

**Comment by thejameskyle** [comment]
It was answering the question, you're asking a new question.

```js
export default function ({types: t}) {
  return {
    visitor: {
      Program(path, state) {
        console.log(state.file.opts.filename);
      }
    }
  };
}
```

**Comment by nescalante** [comment]
thanks! that worked for me now
