### ISSUE TITLE
Translation Request: Slovak

### ISSUE THREAD

**Issue by miluoshi** [thejameskyle/babel-handbook#71]
I am able to translate this language: [yes]

I'll translate it by myself. I just need a Slovak translation to be created on Crowdin. 
Thanks

**Comment by thejameskyle** [comment]
Done, sorry I didn't get to it right away

**Comment by thejameskyle** [comment]
Let me know if you need anything while translating

**Comment by ev1stensberg** [comment]
@miluoshi Let me know if you're in Norway, I'll buy you a cup of coffee :facepunch:

**Comment by miluoshi** [comment]
Haha thanks @ev1stensberg, be sure that I will remember this offer when I will head to Norway. Thanks :)
I've just got to start translating it only now, but still better than never.
