### ISSUE TITLE
Mention inherits for plugin creation

### ISSUE THREAD

**Issue by hzoo** [thejameskyle/babel-handbook#79]
Ref https://github.com/trueadm/babel-plugin-inferno/issues/20

Just so people know about it instead of asking users to supply it

**Comment by thejameskyle** [comment]
Not sure how to explain this one to people. I assume inherits just merges the two visitors.

**Comment by hzoo** [comment]
Added https://github.com/thejameskyle/babel-handbook/blob/master/translations/en/plugin-handbook.md#-enabling-syntax-in-plugins for the specific question about syntax since that's where the question came about
