### ISSUE TITLE
Add API and doc for path.skip() / path.stop()

### ISSUE THREAD

**Issue by hax** [thejameskyle/babel-handbook#86]
These are very simple but very useful APIs for many cases!

I know someone do not know these APIs and invent their own hack like add some flags or check `loc` prop on nodes. I myself waste several hours to read into the source code of babel-traverse with painful "guess -> try -> fail -> guess again" loop...

**Comment by hzoo** [comment]
Added some stuff in https://github.com/thejameskyle/babel-handbook/blob/master/translations/en/plugin-handbook.md#stopping-traversal
