### ISSUE TITLE
The Note on the pre-release of Babel is now useless

### ISSUE THREAD

**Issue by forresst** [thejameskyle/babel-handbook#87]
In the section [Linting](https://github.com/thejameskyle/babel-handbook/blob/master/translations/en/user-handbook.md#linting), i think that the Note on the pre-release of Babel is now useless (The link "latest" now points to the v6.0.5):
>Note: babel-eslint compatibility with Babel 6 is currently in a pre-release version. Install the latest 5.0 beta in order to use it with Babel 6.

If you agree with me, I can do a PR to remove this note.

**Comment by hzoo** [comment]
Sounds good
