### ISSUE TITLE
Korean translation was done!

### ISSUE THREAD

**Issue by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [thejameskyle/babel-handbook#92]
I sent e-mail to me@thejameskyle.com, but I have heard nothing yet.

I Recently I worked with the babel-handbook (plugin-handbook.md),
and I completed Korean translation of the parts of the handbook that were yet to be translated.

As your contributing guide,
(https://github.com/thejameskyle/babel-handbook/blob/master/CONTRIBUTING.md)
I worked in crowdin
(https://crowdin.com/project/babel-plugin-handbook/ko#)
with the same name(Alfred UC) and ID(b6pzeusbc54tvhw5jgpyw8pwz2x6gs)

I gently request merge that translation to the handbook master branch.
Thanks a lot.

**Comment by thejameskyle** [comment]
Sorry, you got spammed for some reason. I'm surprised crowdin didn't sync automatically when you finished your translations. I'll go kick it

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
Oh my god. I thought that because my hash code e-mail, it can be spammer.
Thanks for kicking that !

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
It seems like to be processed well.
